apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-selinux
  namespace: hummingbird-builds
  labels:
    app: nodejs-selinux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-selinux
  template:
    metadata:
      labels:
        app: nodejs-selinux
    spec:
      containers:
        - name: app
          image: REPLACE_WITH_REGISTRY/workshopuser/secure-nodejs:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seLinuxOptions:
              type: hummingbird_nodejs.process
